spring:
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: true
      names: importPersonJob
  sql:
    init:
      mode: ALWAYS
  datasource:
    #    url: 'jdbc:h2:mem:testdb'
    url: 'jdbc:h2:file:./people-import.db'
    driver-class-name: org.h2.Driver
    username: sa
    # password: password
